FROM debian:trixie-backports as builder
ENV BUILD_TYPE=Release
ENV BUILD_DIRECTORY=cmake-build

WORKDIR /app
COPY . .

RUN apt update && apt install -y g++ make cmake

CMD "cmake . -B /app/$BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=$BUILD_TYPE && cmake --build /app/$BUILD_DIRECTORY"