FROM python:3.14.0rc3-slim-trixie as runtime

ENV WHISPERPY_LIBRARY_MODE=Development

# Add support for OpenMP
RUN apt update && apt install -y libgomp1

WORKDIR /app
COPY . . 

CMD ["sh", "-c", "./tests/runall.sh"]